<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('products')->insert([
            // =================================================================
            // Kategori 1: Makanan Ringan
            // =================================================================
            [
                'category_id' => 1,
                'name' => 'Qtela Singkong Original 60g',
                'stock' => 150,
                'cost_price' => 4500,
                'price' => 5500,
                'sku' => 'QT-SK-ORI-60',
                'barcode' => '8992761132214',
                'description' => 'Keripik singkong renyah rasa original.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-05-01',
            ],
            [
                'category_id' => 1,
                'name' => 'Indomie Goreng Original',
                'stock' => 200,
                'cost_price' => 2800,
                'price' => 3500,
                'sku' => 'IND-GR-ORI-85',
                'barcode' => '089686040011',
                'description' => 'Mi instan goreng rasa original legendaris.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-06-15',
            ],
            [
                'category_id' => 1,
                'name' => 'Chitato Sapi Panggang 68g',
                'stock' => 120,
                'cost_price' => 8500,
                'price' => 10000,
                'sku' => 'CHT-SP-68',
                'barcode' => '8998866110037',
                'description' => 'Keripik kentang dengan bumbu sapi panggang.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-07-20',
            ],
            [
                'category_id' => 1,
                'name' => 'Lays Rumput Laut 68g',
                'stock' => 90,
                'cost_price' => 8500,
                'price' => 10000,
                'sku' => 'LYS-RL-68',
                'barcode' => '8992761158016',
                'description' => 'Keripik kentang tipis rasa rumput laut.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-08-10',
            ],
            [
                'category_id' => 1,
                'name' => 'Silverqueen Cashew 58g',
                'stock' => 80,
                'cost_price' => 10000,
                'price' => 12500,
                'sku' => 'SVQ-CS-58',
                'barcode' => '8991001101119',
                'description' => 'Cokelat susu dengan kacang mede.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-09-15',
            ],
            [
                'category_id' => 1,
                'name' => 'Beng-Beng Regular 20g',
                'stock' => 300,
                'cost_price' => 1500,
                'price' => 2000,
                'sku' => 'BBG-REG-20',
                'barcode' => '8996001300018',
                'description' => 'Wafer karamel renyah berlapis cokelat.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-10-30',
            ],
            [
                'category_id' => 1,
                'name' => 'Tango Wafer Cokelat 130g',
                'stock' => 70,
                'cost_price' => 6000,
                'price' => 7500,
                'sku' => 'TGO-CK-130',
                'barcode' => '8991001201017',
                'description' => 'Wafer renyah dengan krim cokelat tebal.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-11-25',
            ],
            [
                'category_id' => 1,
                'name' => 'Pringles Original 107g',
                'stock' => 50,
                'cost_price' => 20000,
                'price' => 24000,
                'sku' => 'PRG-ORI-107',
                'barcode' => '038000138435',
                'description' => 'Keripik kentang dalam tabung rasa original.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-12-05',
            ],
            [
                'category_id' => 1,
                'name' => 'Oishi Pillows Cokelat 100g',
                'stock' => 100,
                'cost_price' => 7000,
                'price' => 8500,
                'sku' => 'OIS-PLC-100',
                'barcode' => '8995166102148',
                'description' => 'Biskuit renyah dengan isian krim cokelat.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-12-25',
            ],
            [
                'category_id' => 1,
                'name' => 'Nabati Wafer Keju 50g',
                'stock' => 180,
                'cost_price' => 1500,
                'price' => 2000,
                'sku' => 'NBT-KJ-50',
                'barcode' => '8993175535017',
                'description' => 'Wafer renyah dengan krim keju richeese.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-11-15',
            ],

            // =================================================================
            // Kategori 2: Minuman
            // =================================================================
            [
                'category_id' => 2,
                'name' => 'Aqua Air Mineral 600ml',
                'stock' => 300,
                'cost_price' => 2500,
                'price' => 3500,
                'sku' => 'AQA-MIN-600',
                'barcode' => '8992761141124',
                'description' => 'Air mineral murni dalam kemasan botol 600ml.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-01-15',
            ],
            [
                'category_id' => 2,
                'name' => 'Teh Kotak Sosro 200ml',
                'stock' => 250,
                'cost_price' => 3000,
                'price' => 4000,
                'sku' => 'SOS-TK-200',
                'barcode' => '8998899000108',
                'description' => 'Minuman teh melati siap saji.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2026-010-01',
            ],
            [
                'category_id' => 2,
                'name' => 'Coca-Cola Kaleng 330ml',
                'stock' => 150,
                'cost_price' => 4500,
                'price' => 6000,
                'sku' => 'CC-KLG-330',
                'barcode' => '8992761101111',
                'description' => 'Minuman soda rasa kola dalam kemasan kaleng.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2025-08-25',
            ],
            [
                'category_id' => 2,
                'name' => 'Fanta Strawberry Botol 390ml',
                'stock' => 130,
                'cost_price' => 4000,
                'price' => 5500,
                'sku' => 'FNT-ST-390',
                'barcode' => '8992761102224',
                'description' => 'Minuman soda rasa stroberi.',
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'expiry_date' => '2025-09-30',
            ],
            // ... kamu bisa lanjutkan data yang lain seperti di atas ...
        ]);
    }
}
